const { buildDamageContext } = require('./damageContext')
const {
  getComboMul,
  collectBuffMultipliers,
  getEnemyDefense,
  calcCritFromCtx,
  resolveCritFromCtx,
  calcDamagePerAttr,
  calcHealFromCtx,
  calcTotalDamage,
  calcPetDisplayBreakdown,
} = require('./damageFormula')
const { estimateDamage } = require('./damageEstimator')
const { resolveSkillDamage, commitSkillDamage } = require('./skillDamageResolver')
const {
  applyStunToEnemy,
  applyFreezeToEnemy,
  applyStunToHero,
  isEnemyControlBuff,
  findEnemyControlBuff,
} = require('./stunResolver')
const { commitBattleVictory } = require('./victoryResolver')
const {
  getAttrColor,
  getEnemyCenterY,
  getPetIconCenter,
  emitNotice,
  emitFloat,
  emitShake,
  emitFlash,
  emitCast,
  emitPetSkillIntro,
  emitPetSkillEffect,
  emitBuffExpire,
  emitPetBadge,
} = require('./fxEmitter')

module.exports = {
  buildDamageContext,
  getComboMul,
  collectBuffMultipliers,
  getEnemyDefense,
  calcCritFromCtx,
  resolveCritFromCtx,
  calcDamagePerAttr,
  calcHealFromCtx,
  calcTotalDamage,
  calcPetDisplayBreakdown,
  estimateDamage,
  resolveSkillDamage,
  commitSkillDamage,
  applyStunToEnemy,
  applyFreezeToEnemy,
  applyStunToHero,
  isEnemyControlBuff,
  findEnemyControlBuff,
  commitBattleVictory,
  getAttrColor,
  getEnemyCenterY,
  getPetIconCenter,
  emitNotice,
  emitFloat,
  emitShake,
  emitFlash,
  emitCast,
  emitPetSkillIntro,
  emitPetSkillEffect,
  emitBuffExpire,
  emitPetBadge,
}
